### ISSUE TITLE
Signer wrapping for JWT signing should scale recovery param

### ISSUE THREAD

**Issue by mirceanis** [uport-project/react-native-signer-demo#4]
The signature produced for JWT signing has recovery param in the range `27`-`28`
But the credentials library does not handle that range when verifying JWTs. It requires the range to be `0`-`1` so the example code should reflect that.

The line in question:
https://github.com/uport-project/react-native-signer-demo/blob/c0d780151d191bf59f1299d5004554c20365fefe/components/HDSigner/credentials.js#L26

It's wise to include a range check too because the recovery param may change in future releases

**Comment by aldigjo** [comment]
resolved by https://github.com/uport-project/react-native-signer-demo/pull/5
